export const UPDATE_LOCAL_QUERYURL = 'UPDATE_LOCAL_QUERYURL'
export const UPDATE_LOCAL_STATIONNAME = 'UPDATE_LOCAL_STATIONNAME'
export const UPDATE_LOCAL_LOGINMODEL = 'UPDATE_LOCAL_LOGINMODEL'
export const UPDATE_LOCAL_TASKDATA = 'UPDATE_LOCAL_TASKDATA'
